user_secret_rewards:
  random_pet_quotes:
    - "I once tried to become a wizard. It didn't work. Now I’m a magical couch potato." # Dog Wizard
    - "The world is my tuna... just kidding, I’m too tired to do anything." # Cat Barbarian
    - "I haven't seen you in ages! I almost thought you'd abandoned me!" # Hamster Assassin
    - "I’d rather sleep than fight. But I guess fighting is part of the job." # Pig Paladin
    - "I raised an army of rabbits once. Turns out they’re better at burrowing than fighting." # Rabbit Necromancer
    - "Sometimes I wonder if the squirrels are secretly judging me. I don't trust them." # Squirrel Bard

  dream_sequences:
    hamster_assassin:
      - "The hamster dreams of a world where hamsters rule the universe. They wake up feeling faster."
      - "Hamster falls asleep and dreams of chasing a giant, rolling wheel. It gets an agility boost."
    dog_wizard:
      - "The dog dreams of an army of squirrels. When it wakes up, it’s suddenly full of magical energy."
      - "Dog Wizard dreams of becoming the head of the Wizard Council. It wakes up inspired, granting a temporary magic boost."
    rabbit_necromancer:
      - "The rabbit dreams of creating an army of undead carrots. It wakes up with newfound necromantic power."
      - "The rabbit dreams of summoning the ancient spirits of fallen bunnies. It wakes up with a mysterious, dark energy."
    squirrel_bard:
      - "Squirrel dreams of performing a concert for a crowd of thousands. It wakes up with increased morale."
      - "The squirrel dreams of writing the perfect song, gaining a boost to its creativity and wit."

  forgotten_items:
    hamster_assassin:
      - name: "Hidden Knife"
        effect: "+5 agility for the next pet"
        description: "A tiny, hidden knife that Hamster Assassin never leaves without. It's sharp and speedy."
    dog_wizard:
      - name: "Wizard's Bone"
        effect: "+2 intelligence for the next pet"
        description: "An ancient bone from Dog Wizard’s early adventures, filled with forgotten magical secrets."
    cat_barbarian:
      - name: "Tuna of Victory"
        effect: "+5 strength for the next pet"
        description: "A half-eaten tuna that Cat Barbarian once left behind. It still holds some power."
    pig_paladin:
      - name: "Mud Shield"
        effect: "+5 defense for the next pet"
        description: "A shield made from mud and bravery. Pig Paladin’s legacy of defense."
    rabbit_necromancer:
      - name: "Carrot of the Dead"
        effect: "+2 intelligence for the next pet"
        description: "A carrot that channels necromantic power, capable of summoning undead allies."
    squirrel_bard:
      - name: "Lute of Echoing"
        effect: "+2 agility for the next pet"
        description: "A lute with magical strings, capable of enchanting all who hear its song."

  hidden_backstories:
    hamster_assassin:
      - "Hamster Assassin once assassinated a sandwich before anyone realized it was missing."
      - "Hamster Assassin had a brief but successful career in the cheese industry before returning to assassin life."
    dog_wizard:
      - "Dog Wizard was once cursed by an ancient cat witch, which is why it’s always a little grumpy."
      - "Dog Wizard’s magic failed during an epic battle, but it still saved the day by fetching a magical sword."
    cat_barbarian:
      - "Cat Barbarian once ate an entire tuna in one sitting and fell asleep for a week."
      - "Cat Barbarian was part of a legendary battle where it took out ten enemies while napping."
    pig_paladin:
      - "Pig Paladin's first battle was with a tiny mouse. It won, but it still respects the mouse to this day."
      - "Pig Paladin’s favorite childhood toy was a mud pie. It’s still considered the greatest weapon of all."
    rabbit_necromancer:
      - "Rabbit Necromancer once raised an army of skeletons to fight a rogue carrot invasion."
      - "Rabbit Necromancer is the last of its kind, carrying the ancient magic of forbidden carrots."
    squirrel_bard:
      - "Squirrel Bard once sang a lullaby to a fierce bear, only to find out the bear was already asleep."
      - "Squirrel Bard composed a song so beautiful, it made a tree cry. The tree still weeps to this day."
