places_to_die:
  - "In a hamster wheel, running forever."
  - "Trapped in a hammock by a rogue sloth."
  - "Buried under a pile of overcooked spaghetti."
  - "Swallowed whole by a rubber duck."
  - "During a high-speed chase with a velociraptor on roller skates."
  - "While being the star of a reality TV show about squirrels."
  - "In an elevator that only stops at the worst possible floors."
  - "In the middle of a pillow fight with a ninja."
  - "Accidentally catapulted into a vat of mashed potatoes."
  - "Falling into an enormous pot of boiling tea made by angry bees."

ways_to_die:
  - "Suffocated by a rogue marshmallow."
  - "Pushed off a cliff by an overzealous penguin."
  - "Trampled by an army of inflatable flamingos."
  - "Eaten by a swarm of overly friendly goats."
  - "Struck by lightning while wearing aluminum foil armor."
  - "Licked to death by a giant dog covered in chocolate syrup."
  - "Accidentally crushed under a pile of giant rubber ducks."
  - "Caught in a never-ending loop of awkward hugs."
  - "Run over by a herd of roller-skating clowns."
  - "Drowned in a pool of unspent confetti."

times_to_die:
  - "At 3:27 PM while eating a very large sandwich."
  - "Right before the final season of your favorite show airs."
  - "During a nap, at precisely 12:01 PM."
  - "When the clock strikes midnight and you’re trying to make a toast."
  - "Exactly 5 minutes after finding the perfect parking spot."
  - "While trying to untangle the Christmas lights in mid-January."
  - "Right before your online order of pizza arrives."
  - "At the exact moment your favorite TV character dies."
  - "During the last minute of your 12-hour Netflix binge."
  - "While you’re making an epic TikTok dance video."
